language: ruby
cache: bundler
rvm:
  - 2.1.2
bundler_args: --without development
env: DATABASE_URL=postgres://127.0.0.1:5432/pgperf_test
before_script:
  - createdb pgperf_test
  - bundle exec rake db:migrate
script: bundle exec rspec
services:
  - redis-server
addons:
  postgresql: "9.3"
