language: ruby
cache: bundler
rvm:
  - 2.1.2
bundler_args: --without development
env: DATABASE_URL=postgres://127.0.0.1:5432/pgperf_test
before_script:
  - createdb pgperf_test
  - bundle exec rake db:migrate
script: bundle exec rspec
services:
  - redis-server
addons:
  postgresql: "9.3"
  code_climate:
      repo_token: 37bd35737223ea87b24c94b54fc3cc3b2ce9b2cb89dd2af50da2c95ec997cf8e
